"""empty message

Revision ID: 9f43635fe09b
Revises: a84e2f87c7a2
Create Date: 2017-08-23 03:51:43.782912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f43635fe09b'
down_revision = 'a84e2f87c7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('create_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'create_at')
    # ### end Alembic commands ###
